repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json

  - repo: local
    hooks:
      - id: format
        name: format python
        entry: task format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint python
        entry: task lint
        language: system
        types: [python]
        pass_filenames: false

      - id: typecheck
        name: typecheck python
        entry: task typecheck
        language: system
        types: [python]
        pass_filenames: false

      - id: format-verilog
        name: format verilog
        entry: task format-verilog
        language: system
        files: '\.(s?v)$'
        pass_filenames: false

      - id: lint-verilog
        name: lint verilog
        entry: task lint-verilog
        language: system
        files: '\.(s?v)$'
        pass_filenames: false

      - id: lint-rtl
        name: lint rtl
        entry: task lint-rtl
        language: system
        files: '\.(s?v)$'
        pass_filenames: false
